# Generated by Django 5.0.1 on 2024-01-16 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('current_vehicle', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('year_date', models.DateField()),
                ('fuel', models.CharField(choices=[('P', 'Premium'), ('R', 'Regular'), ('M', 'Mid-Grade')], default='R', max_length=1)),
                ('carbon', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('departure', models.TextField(max_length=255)),
                ('destination', models.TextField(max_length=255)),
                ('co_em', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.vehicle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
