# Generated by Django 5.0.1 on 2024-01-14 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='auth_id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='carbon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.user'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(choices=[('P', 'Premium'), ('R', 'Regular'), ('M', 'Mid-Grade')], default='R', max_length=1),
        ),
    ]
