# Generated by Django 5.0.1 on 2024-01-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distances',
            name='duration_mins',
            field=models.IntegerField(default=0),
        ),
    ]
