# Generated by Django 5.0.1 on 2024-01-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_distances_duration_mins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distances',
            name='duration_mins',
        ),
    ]
