# Generated by Django 5.0.1 on 2024-01-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_trip_options_remove_user_auth_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_vehicle',
            field=models.IntegerField(null=True),
        ),
    ]
