# Generated by Django 5.0.1 on 2024-01-18 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_locations_lat_locations_lng_locations_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Distances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, max_length=200, null=True)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_mins', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_traffic_mins', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='main_app.locations')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='main_app.locations')),
            ],
        ),
    ]
