# Generated by Django 5.0.1 on 2024-01-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_locations_created_at_distances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distances',
            name='mode',
        ),
    ]
